name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Test Frontend
        working-directory: frontend
        run: |
          npm ci
          npm test

      - name: Install and Test Backend
        working-directory: backend
        run: |
          npm ci
          npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install and Build Frontend
        run: |
          cd frontend
          npm ci
          npm run build
          cd ..

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
        shell: bash

      - name: Deploy Frontend
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r frontend/dist/* ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_HOST }}:/var/www/html/frontend
        shell: bash

      - name: Restart Frontend Service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.FRONTEND_HOST }} "sudo systemctl restart frontend"
        shell: bash

      - name: Deploy Backend
        run: |
          scp -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa -r backend/* ${{ secrets.SSH_USER }}@${{ secrets.BACKEND_HOST }}:/home/ubuntu/app/backend
        shell: bash

      - name: Restart Backend Service
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ secrets.SSH_USER }}@${{ secrets.BACKEND_HOST }} "sudo systemctl restart backend"
        shell: bash
